# Generated by OmopViewer 0.7.0
# Be careful editing this file

library(bslib)
library(CodelistGenerator)
library(CohortCharacteristics)
library(DiagrammeR)
library(DiagrammeRsvg)
library(dplyr)
library(DT)
library(ggplot2)
library(gt)
library(markdown)
library(omopgenerics)
library(OmopSketch)
library(plotly)
library(purrr)
library(reactable)
library(rlang)
library(rsvg)
library(shiny)
library(shinycssloaders)
library(shinyWidgets)
library(sortable)
library(tidyr)
library(visOmopResults)
library(yaml)

#nm <- ""
nm <- "acute_mi_narrow"
#nm <- "stroe_broad"

fileData <- file.path(getwd(), "data", paste0("studyData_", nm, ".RData"))
# load shiny data
load(fileData)

# source functions
source(file.path(getwd(), "functions.R"))
