---
title: "MI/Stroke Inpatient"
format: html
  # docx:
  #   fig-cap-location: top
execute:
  echo: false
  message: false
  warning: false
lof: true
---

```{r}
# Load necessary packages ----
library(OmopSketch)
library(visOmopResults)
library(dplyr)
library(omopgenerics)
library(flextable)
library(ggplot2)

# Load results stored in the package ----
fileData <- file.path(getwd(), "data", "studyData.RData")
if (!file.exists(fileData)) {
  source(file.path(getwd(), "rawData", "preprocess.R"))
}

# uncomment to load the raw data
# rawData <- omopgenerics::importSummarisedResult(file.path(getwd(), "rawData"))

# load data
load(fileData)

# source functions
source(file.path(getwd(), "functions.R"))

# Global options ----
knitr::opts_chunk$set(
  out.width  = "95%",  # figures occupy ~95% of document width
  out.height = "auto",
  dpi        = 320,    # ensure figure quality
  fig.width  = 6,      # default aspect ratio (can be overridden per-figure)
  fig.height = 3,
  results    = "asis"  # enable Markdown produced via cat() inside chunks
)

setGlobalPlotOptions(type = "ggplot")
setGlobalTableOptions(type = "flextable")
tt <- "flextable"
```

:::{custom-style="Caption"}
**Table 1:** Database metadata.
:::

```{r}
OmopSketch::tableOmopSnapshot(data[["summarise_omop_snapshot"]], type = tt)
```

:::{custom-style="Caption"}
**Table 2:** Demographics characterisation at first record of Myocardial infarction.
:::

```{r}
arrangeCharacteristics <- function(x) {
  x |>
    dplyr::mutate(order_id = dplyr::case_when(
      variable_name == "Number records" ~ 1L,
      variable_name == "Number subjects" ~ 2L,
      variable_name == "Sex" ~ 5L,
      variable_name == "Age" ~ 6L,
      variable_name == "Age group" ~ 7L,
      variable_name == "Ethnicity group" ~ 8L,
      variable_name == "SES" ~ 9L,
      variable_name == "MI type" ~ 12L
    )) |>
    dplyr::arrange(order_id, variable_level) |>
    dplyr::select(!"order_id")
}
data$summarise_demographics |>
  filter(
    variable_name %in% c(
      "Number records", "Number subjects", "Sex", "Age", "Age group",
      "Ethnicity group", "SES", "MI type", "Socio-economic status"
    ),
    variable_level != "Male" | is.na(variable_level),
    !estimate_name %in% c("median", "q25", "q75", "min", "max"),
    group_level %in% c(
      "Acute Ischemic Stroke", "Acute Myocardial Infarction"
    ),
    strata_level == "overall"
  ) |>
  arrange(group_level, cdm_name) |>
  arrangeCharacteristics() |>
  mutate(
    variable_level = coalesce(variable_level, variable_name),
    variable_name = case_when(
      variable_name == "Age group" ~ "Age group — N(%)",
      variable_name == "Ethnicity group" ~ "Ethnicity — N(%)",
      variable_name == "Socio-economic status" ~ "Socio-economic status — N(%)",
      .default = "Demographics"
    ),
    variable_level = if_else(
      variable_name == "Demographics",
      case_when(
        variable_level == "Number records" ~ "Number records — N",
        variable_level == "Number subjects" ~ "Number subjects — N",
        variable_level == "Female" ~ "Female — N (%)",
        variable_level == "Age" ~ "Age — Mean (SD)",
        .default = variable_level
      ),
      variable_level
    )
  ) |>
  CohortCharacteristics::tableCharacteristics(
    hide = c("strata", "table_name", "age_range", "ses", "sex", "mi_type", "estimate_name"),
    header = c("cohort_name", "cdm_name"),
    groupColumn = "variable_name",
    type = tt
  )
```

:::{custom-style="Caption"}
**Table 3:** Medications.
:::

```{r}
data$summarise_treatments |>
  filter(
    group_level %in% c(
      "Acute Ischemic Stroke", "Acute Myocardial Infarction"
    ),
    strata_level == "overall"
  ) |>
  arrange(group_level, cdm_name) |>
  arrangeCharacteristics() |>
  CohortCharacteristics::tableCharacteristics(
    hide = c("variable_name", "strata", "table_name", "age_range", "ses", "sex", "mi_type", "estimate_name"),
    header = c("cohort_name", "cdm_name"),
    type = tt
  )
```

```{r}
x <- data$summarise_treatments |>
  tidy() |>
  filter(
    cohort_name == "Acute Myocardial Infarction",
    !grepl("cangrelor", variable_level),
    grepl("P2y12", variable_level),
    grepl("Sex", strata),
    !grepl("STEMI", cohort_name)
  ) |>
  mutate(
    drug = if_else(
      variable_level == "P2y12 inhibitors",
      "overall",
      gsub("P2y12 inhibitors ", "", variable_level)
    ) |>
      factor(c("overall", "clopidogrel", "prasugrel", "ticagrelor")),
    sex = gsub("Sex: ", "", strata)
  )
p <- ggplot(data = x, mapping = aes(x = drug, y = percentage, fill = sex)) +
  geom_col(position = "dodge") +
  facet_grid(. ~ cdm_name) +
  labs(fill = "", y = "Percentage (%)", x = "") +
  theme_bw()
stylePlot(p) +
  theme(legend.position = "top")
```

:::{custom-style="Caption"}
**Figure 1:** P2Y12 inhibitors for AMI.
:::

```{r}
x <- data$summarise_treatments |>
  tidy() |>
  filter(
    cohort_name == "Acute Ischemic Stroke",
    variable_level %in% c("Doacs", "Warfarin"),
    grepl("Age", strata)
  ) |>
  mutate(
    drug = if_else(
      variable_level == "Doacs",
      "DOACs",
      "Warfarin"
    ),
    age = gsub("Age group: ", "", strata)
  )
p <- ggplot(data = x, mapping = aes(x = drug, y = percentage, fill = age)) +
  geom_col(position = "dodge") +
  facet_grid(. ~ cdm_name) +
  labs(fill = "Age group", y = "Percentage (%)", x = "") +
  theme_bw()
stylePlot(p) +
  theme(legend.position = "top")
```

:::{custom-style="Caption"}
**Figure 2:** Warfarin and DOACS for Stroke.
:::

```{r}
x <- data$summarise_treatments |>
  tidy() |>
  filter(
    variable_level == "Statin",
    !grepl("STEMI", cohort_name),
    grepl("Sex", strata)
  ) |>
  mutate(sex = gsub("Sex: ", "", strata), variable_level = "")
p <- ggplot(data = x, mapping = aes(x = variable_level, y = percentage, fill = sex)) +
  geom_col(position = "dodge") +
  facet_grid(cohort_name ~ cdm_name) +
  labs(fill = "Sex", y = "Percentage (%)", x = "") +
  theme_bw()
stylePlot(p) +
  theme(legend.position = "top", strip.text.y.right = element_text(angle = -90))
```

:::{custom-style="Caption"}
**Figure 3:** Statins by sex.
:::

:::{custom-style="Caption"}
**Table 4:** Procedures.
:::

```{r}
data$summarise_procedures |>
  filter(
    strata_level == "overall",
    grepl("Procedures", variable_name),
    !grepl("IDRIL", cdm_name)
  ) |>
  arrange(group_level, cdm_name) |>
  CohortCharacteristics::tableCharacteristics(
    hide = c("variable_name", "strata", "table_name", "age_range", "ses", "sex", "mi_type", "estimate_name"),
    header = c("cdm_name"),
    groupColumn = "cohort_name",
    type = tt
  )
```

# radial plots


