# Generated by OmopViewer 0.7.0
# Be careful editing this file

server <- function(input, output, session) {

  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )

  # summarise_omop_snapshot -----
  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::reactive({
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )

  # summarise_observation_period -----
  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::reactive({
    data[["summarise_observation_period"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name
      )
  })
  getSummariseObservationPeriodTable <- shiny::reactive({
    res <- getSummariseObservationPeriodData()
    res |>
      OmopSketch::tableObservationPeriod(
        hide = c(omopgenerics::settingsColumns(res), "observation_period_ordinal"),
      )
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    x <- getSummariseObservationPeriodPlot()
    renderInteractivePlot(x, input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )

  # cohort_code_use -----
  ## get cohort_code_use data
  getCohortCodeUseData <- shiny::reactive({
    data[["cohort_code_use"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$cohort_code_use_cdm_name,
        .data$estimate_name %in% input$cohort_code_use_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$codelist_name %in% input$cohort_code_use_codelist_name
      )
  })
  getCohortCodeUseTableReact <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        type = "reactable",
        header = "cdm_name"
      )
  })
  output$cohort_code_use_table_react <- reactable::renderReactable({
    getCohortCodeUseTableReact()
  })
  getCohortCodeUseTableGt <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        hide = "timing"
      )
  })
  output$cohort_code_use_table_gt <- gt::render_gt({
    getCohortCodeUseTableGt()
  })
  output$cohort_code_use_table_gt_download <- shiny::downloadHandler(
    filename = paste0("table_cohort_code_use.", input$cohort_code_use_table_gt_format),
    content = function(file) {
      gt::gtsave(getCohortCodeUseTableGt(), file)
    }
  )

  # summarise_cohort_count -----
  ## get summarise_cohort_count data
  getSummariseCohortCountData <- shiny::reactive({
    data[["summarise_cohort_count"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_count_cdm_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_count_cohort_name) |>
      dplyr::filter(variable_name == "Number subjects")
  })
  getSummariseCohortCountTable <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::tableCohortCount(
        header = "cdm_name",
        groupColumn = c("cohort_name"),
        hide = c("variable_level", "table_name", "estimate_name")
      )
  })
  output$summarise_cohort_count_table <- gt::render_gt({
    getSummariseCohortCountTable()
  })
  output$summarise_cohort_count_table_download <- shiny::downloadHandler(
    filename = paste0("table_count.", input$summarise_cohort_count_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortCountTable(), file)
    }
  )
  getSummariseCohortCountPlot <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::plotCohortCount(
        facet = input$summarise_cohort_count_plot_facet,
        colour = input$summarise_cohort_count_plot_colour
      )
  })
  output$summarise_cohort_count_plot <- shiny::renderUI({
    x <- getSummariseCohortCountPlot()
    renderInteractivePlot(x, input$summarise_cohort_count_plot_interactive)
  })
  output$summarise_cohort_count_plot_download <- shiny::downloadHandler(
    filename = "plot_count.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortCountPlot(),
        width = as.numeric(input$summarise_cohort_count_plot_width),
        height = as.numeric(input$summarise_cohort_count_plot_height),
        units = input$summarise_cohort_count_plot_units,
        dpi = as.numeric(input$summarise_cohort_count_plot_dpi)
      )
    }
  )

  # summarise_cohort_attrition -----
  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::reactive({
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_attrition_cohort_name)
  })
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition()
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )

  # summarise_demographics -----
  ## get summarise_demographics data
  getSummariseDemographicsData <- shiny::reactive({
    data[["summarise_demographics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_demographics_cdm_name,
        .data$variable_name %in% input$summarise_demographics_variable_name,
        .data$estimate_name %in% input$summarise_demographics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_demographics_cohort_name) |>
      omopgenerics::filterStrata(
        .data$strata %in% input$summarise_demographics_strata
      )
  })
  getSummariseDemographicsTable <- shiny::reactive({
    getSummariseDemographicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_demographics_table_header,
        groupColumn = input$summarise_demographics_table_group_column,
        hide = unique(c("index_condition", "drug", "table_name", input$summarise_demographics_table_hide))
      )
  })
  output$summarise_demographics_table <- gt::render_gt({
    getSummariseDemographicsTable()
  })
  output$summarise_demographics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_demographics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseDemographicsTable(), file)
    }
  )
  getSummariseDemographicsPlot <- shiny::reactive({
    getSummariseDemographicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_demographics_plot_plot_type,
        facet = input$summarise_demographics_plot_facet,
        colour = input$summarise_demographics_plot_colour
      )
  })
  output$summarise_demographics_plot <- shiny::renderUI({
    x <- getSummariseDemographicsPlot()
    renderInteractivePlot(x, input$summarise_demographics_plot_interactive)
  })
  output$summarise_demographics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseDemographicsPlot(),
        width = as.numeric(input$summarise_demographics_plot_width),
        height = as.numeric(input$summarise_demographics_plot_height),
        units = input$summarise_demographics_plot_units,
        dpi = as.numeric(input$summarise_demographics_plot_dpi)
      )
    }
  )

  # summarise_death -----
  ## get summarise_death data
  getSummariseDeathData <- shiny::reactive({
    data[["summarise_death"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_death_cdm_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_death_cohort_name) |>
      omopgenerics::filterStrata(
        .data$strata %in% input$summarise_death_strata
      )
  })
  getSummariseDeathTable <- shiny::reactive({
    getSummariseDeathData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_death_table_header,
        groupColumn = input$summarise_death_table_group_column,
        hide = unique(c("index_condition", "drug", "table_name", "variable_level", input$summarise_death_table_hide))
      )
  })
  output$summarise_death_table <- gt::render_gt({
    getSummariseDeathTable()
  })
  output$summarise_death_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_death_table_format),
    content = function(file) {
      gt::gtsave(getSummariseDeathTable(), file)
    }
  )
  getSummariseDeathPlot <- shiny::reactive({
    getSummariseDeathData() |>
      dplyr::filter(.data$estimate_name == "percentage") |>
      CohortCharacteristics::plotCharacteristics(
        plotType = "barplot",
        facet = input$summarise_death_plot_facet,
        colour = input$summarise_death_plot_colour
      )
  })
  output$summarise_death_plot <- shiny::renderUI({
    x <- getSummariseDeathPlot()
    renderInteractivePlot(x, input$summarise_death_plot_interactive)
  })
  output$summarise_death_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseDeathPlot(),
        width = as.numeric(input$summarise_death_plot_width),
        height = as.numeric(input$summarise_death_plot_height),
        units = input$summarise_death_plot_units,
        dpi = as.numeric(input$summarise_death_plot_dpi)
      )
    }
  )

  # summarise_treatments -----
  ## get summarise_treatments data
  getSummariseTreatmentsData <- shiny::reactive({
    data[["summarise_treatments"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_treatments_cdm_name,
        .data$variable_name %in% input$summarise_treatments_variable_name,
        .data$variable_level %in% input$summarise_treatments_variable_level
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_treatments_cohort_name) |>
      omopgenerics::filterStrata(
        .data$strata %in% input$summarise_treatments_strata
      )
  })
  getSummariseTreatmentsTable <- shiny::reactive({
    getSummariseTreatmentsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_treatments_table_header,
        groupColumn = input$summarise_treatments_table_group_column,
        hide = unique(c("index_condition", "drug", "table_name", input$summarise_treatments_table_hide))
      )
  })
  output$summarise_treatments_table <- gt::render_gt({
    getSummariseTreatmentsTable()
  })
  output$summarise_treatments_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_treatments_table_format),
    content = function(file) {
      gt::gtsave(getSummariseTreatmentsTable(), file)
    }
  )
  getSummariseTreatmentsPlot <- shiny::reactive({
    x <- getSummariseTreatmentsData() |>
      omopgenerics::tidy()
    visOmopResults::barPlot(
      result = x,
      x = "variable_level",
      y = "percentage",
      facet = input$summarise_treatments_plot_facet,
      colour = input$summarise_treatments_plot_colour
    ) +
      ggplot2::coord_flip()
  })
  output$summarise_treatments_plot <- shiny::renderUI({
    x <- getSummariseTreatmentsPlot()
    renderInteractivePlot(x, input$summarise_treatments_plot_interactive)
  })
  output$summarise_treatments_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseTreatmentsPlot(),
        width = as.numeric(input$summarise_treatments_plot_width),
        height = as.numeric(input$summarise_treatments_plot_height),
        units = input$summarise_treatments_plot_units,
        dpi = as.numeric(input$summarise_treatments_plot_dpi)
      )
    }
  )

  # summarise_procedures -----
  ## get summarise_procedures data
  getSummariseProceduresData <- shiny::reactive({
    data[["summarise_procedures"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_procedures_cdm_name,
        .data$variable_name %in% input$summarise_procedures_variable_name,
        .data$estimate_name %in% input$summarise_procedures_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_procedures_cohort_name) |>
      omopgenerics::filterStrata(.data$strata %in% input$summarise_procedures_strata)
  })
  getSummariseProceduresTable <- shiny::reactive({
    getSummariseProceduresData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_procedures_table_header,
        groupColumn = input$summarise_procedures_table_group_column,
        hide = unique(c("index_condition", "drug", "table_name", input$summarise_procedures_table_hide))
      )
  })
  output$summarise_procedures_table <- gt::render_gt({
    getSummariseProceduresTable()
  })
  output$summarise_procedures_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_procedures_table_format),
    content = function(file) {
      gt::gtsave(getSummariseProceduresTable(), file)
    }
  )
  getSummariseProceduresPlot <- shiny::reactive({
    x <- getSummariseProceduresData() |>
      omopgenerics::tidy()
    visOmopResults::barPlot(
      result = x,
      x = "variable_level",
      y = "percentage",
      facet = input$summarise_treatments_plot_facet,
      colour = input$summarise_treatments_plot_colour
    ) +
      ggplot2::coord_flip()
  })
  output$summarise_procedures_plot <- shiny::renderUI({
    x <- getSummariseProceduresPlot()
    renderInteractivePlot(x, input$summarise_procedures_plot_interactive)
  })
  output$summarise_procedures_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseProceduresPlot(),
        width = as.numeric(input$summarise_procedures_plot_width),
        height = as.numeric(input$summarise_procedures_plot_height),
        units = input$summarise_procedures_plot_units,
        dpi = as.numeric(input$summarise_procedures_plot_dpi)
      )
    }
  )

  # initiators demographics -----
  getInitiatorsDemoData <- shiny::reactive({
    data[["summarise_drug_initiators"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_drug_initiators_cdm_name
      ) |>
      omopgenerics::filterGroup(
        .data$index_condition %in% input$summarise_drug_initiators_index_condition,
        .data$drug %in% input$summarise_drug_initiators_drug
      )
  })
  getInitiatorsDemoTable <- shiny::reactive({
    getInitiatorsDemoData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_drug_initiators_table_header,
        groupColumn = input$summarise_drug_initiators_table_group_column,
        hide = unique(c("cohort_name", "strata", "table_name", input$summarise_drug_initiators_table_hide))
      )
  })
  output$summarise_drug_initiators_table <- gt::render_gt({
    getInitiatorsDemoTable()
  })
  getInitiatorRRData <- shiny::reactive({
    data$radial |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_drug_initiators_cdm_name,
        .data$index_condition %in% input$summarise_drug_initiators_index_condition,
        .data$drug %in% input$summarise_drug_initiators_drug
      )
  })
  output$summarise_drug_initiators_forest <- shiny::renderPlot({
    x <- getInitiatorRRData()
    labs <- x |>
      dplyr::distinct(variable_level, y)
    ggplot2::ggplot(
      data = x,
      mapping = ggplot2::aes(x = rr, xmin = rr_lower, xmax = rr_upper, y = y, colour = variable_name)
    ) +
      ggplot2::geom_point() +
      ggplot2::geom_errorbar() +
      ggplot2::facet_grid(cdm_name ~ index_condition + drug) +
      ggplot2::geom_vline(xintercept = 1) +
      ggplot2::scale_x_log10(name = "Relative Risk") +
      ggplot2::coord_cartesian(xlim = c(0.5, 2)) +
      ggplot2::scale_y_continuous(
        breaks = labs$y,
        labels = labs$variable_level
      )
  })
  output$summarise_drug_initiators_radial <- shiny::renderPlot({
    x <- getInitiatorRRData() |>
      dplyr::mutate(value = count1 / den1)
    labs <- x |>
      dplyr::distinct(variable_level, y)
    ggplot2::ggplot(
      data = x,
      mapping = ggplot2::aes(x = y, y = value, fill = variable_name)
    ) +
      ggplot2::geom_col() +
      ggplot2::facet_grid(cdm_name ~ index_condition + drug) +
      ggplot2::coord_polar() +
      ggplot2::scale_x_continuous(
        breaks = labs$y,
        labels = labs$variable_level
      )
  })
  # probability to initiate ----
  getDrugInitiateData <- shiny::reactive({
    data$drug_initiate |>
      dplyr::filter(
        .data$cdm_name %in% input$drug_initiate_cdm_name
      ) |>
      omopgenerics::filterGroup(.data$index_condition %in% input$drug_initiate_index_condition) |>
      omopgenerics::filterStrata(.data$drug %in% input$drug_initiate_drug)
  })
  output$drug_initiate_table <- gt::render_gt({
    getDrugInitiateData() |>
      visOmopResults::visOmopTable(
        estimateName = c("RR [95%CI]" = "<rr> [<rr_lower> - <rr_upper>]"),
        header = "cdm_name",
        groupColumn = c("index_condition", "drug"),
        hide = "variable_level"
      )
  })
  output$drug_initiate_plot <- shiny::renderPlot({
    x <- getDrugInitiateData() |>
      omopgenerics::tidy() |>
      dplyr::mutate(variable_level = dplyr::case_when(
        stringr::str_starts(variable_name, "age_group") ~ "age_group",
        stringr::str_starts(variable_name, "sex") ~ "sex",
        stringr::str_starts(variable_name, "ses") ~ "ses",
        stringr::str_starts(variable_name, "ethnicity") ~ "ethnicity",
        stringr::str_starts(variable_name, "mi_type") ~ "mi_type",
      ))
    labs <- x |>
      dplyr::distinct(variable_name) |>
      dplyr::arrange(.data$variable_name) |>
      dplyr::mutate(y = dplyr::row_number())
    x <- x |>
      dplyr::inner_join(labs, by = "variable_name")
    ggplot2::ggplot(
      data = x,
      mapping = ggplot2::aes(x = rr, xmin = rr_lower, xmax = rr_upper, y = y, colour = variable_level)
    ) +
      ggplot2::geom_point() +
      ggplot2::geom_errorbar() +
      ggplot2::facet_grid(cdm_name ~ index_condition + drug) +
      ggplot2::geom_vline(xintercept = 1) +
      ggplot2::scale_x_log10(name = "Relative Risk") +
      ggplot2::coord_cartesian(xlim = c(0.5, 2)) +
      ggplot2::scale_y_continuous(
        breaks = labs$y,
        labels = labs$variable_name
      )
  })

}
